pinaxcon/registrasion/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    "pinaxcon.registrasion.views",
    url(r"^demopay/([0-9]+)/([A-Z0-9]+)$", views.demopay, name="demopay"),
)

pinaxcon/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.contrib.flatpages.views import flatpage

from django.contrib import admin

import symposion.views


urlpatterns = [
    url(r'^saml2/', include('djangosaml2.urls')),
    url(r"^admin/", include(admin.site.urls)),

    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^conference/", include("symposion.conference.urls")),

    url(r"^teams/", include("symposion.teams.urls")),

    # Required by registrasion
    url(r'^tickets/payments/', include('registripe.urls')),
    url(r'^tickets/', include('registrasion.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^checkin/', include('regidesk.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    url(r'^dashboard/', symposion.views.dashboard, name="dashboard"),
    url(r'^boardingpass', RedirectView.as_view(pattern_name="regidesk:boardingpass")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, url(r'^__debug__/', include(debug_toolbar.urls)))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinaxcon/proposals/models.py
from django.db import models

from symposion.proposals.models import ProposalBase


class Proposal(ProposalBase):

    TARGET_USER = 1
    TARGET_BUSINESS = 2
    TARGET_COMMUNITY = 3
    TARGET_DEVELOPER = 4

    TARGET_AUIDENCES = [
        (TARGET_USER, "User"),
        (TARGET_BUSINESS, "Business"),
        (TARGET_COMMUNITY, "Community"),
        (TARGET_DEVELOPER, "Developer"),
    ]

    target_audience = models.IntegerField(choices=TARGET_AUIDENCES)

    recording_release = models.BooleanField(
        default=True,
        help_text="I allow Linux Australia to release any recordings of "
        "presentations covered by this proposal, under the <a "
        "href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> "
        "Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"
    )

    materials_release = models.BooleanField(
        default=True,
        help_text="I allow Linux Australia to release any other material "
        "(such as slides) from presentations covered by this proposal, under "
        "the <a "
        "href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> "
        "Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"
    )

    class Meta:
        abstract = True


class TalkProposal(Proposal):

    class Meta:
        verbose_name = "talk proposal"


class TutorialProposal(Proposal):

    class Meta:
        verbose_name = "tutorial proposal"


class MiniconfProposal(Proposal):

    target_audience = models.IntegerField(choices=Proposal.TARGET_AUIDENCES,
                                          default=Proposal.TARGET_DEVELOPER)

    class Meta:
        verbose_name = "miniconf proposal"


class SysAdminProposal(Proposal):

    TYPE_SHORT_PRESENTATION = 1
    TYPE_LIGHTNING_TALK = 2

    TALK_FORMATS = [
        (TYPE_SHORT_PRESENTATION, "Short Presentation (15-25 min)"),
        (TYPE_LIGHTNING_TALK, "Lightning Talk (5-10 min)"),
    ]

    talk_format = models.IntegerField(
        choices=TALK_FORMATS,
        help_text="Please indicate your preferred talk length in the private abstract field below.")

    class Meta:
        verbose_name = "System Administration Miniconf Proposal"


class KernelProposal(Proposal):

    class Meta:
        verbose_name = "Kernel Miniconf Proposal"


class GamesProposal(Proposal):

    TYPE_PRESENTATION = 1
    TYPE_DEMONSTRATION = 2
    TYPE_OTHER = 3

    TALK_FORMATS = [
        (TYPE_PRESENTATION, "Presentation"),
        (TYPE_DEMONSTRATION, "Demonstration"),
        (TYPE_OTHER, "Other"),
    ]

    talk_format = models.IntegerField(choices=TALK_FORMATS)

    class Meta:
        verbose_name = "Games and FOSS Miniconf Proposal"


class OpenHardwareProposal(Proposal):

    TYPE_NORMAL_PRESENTATION = 1
    TYPE_LIGHTNING_TALK = 2

    TALK_FORMATS = [
        (TYPE_NORMAL_PRESENTATION, "Presentation (20 min)"),
        (TYPE_LIGHTNING_TALK, "Lightning Talk (5 min)"),
    ]

    talk_format = models.IntegerField(choices=TALK_FORMATS)

    class Meta:
        verbose_name = "Open Hardware Miniconf Proposal"


class ClsXLCAProposal(Proposal):

    class Meta:
        verbose_name = "CLSxLCA Miniconf Proposal"


class FuncProgProposal(Proposal):

    class Meta:
        verbose_name = "Real World Functional Programming Miniconf Proposal"


class OpenEdProposal(Proposal):

    class Meta:
        verbose_name = "Open Education Miniconf Proposal"


class OpenGLAMProposal(Proposal):

    class Meta:
        verbose_name = "OpenGLAM Miniconf Proposal"


class FPGAProposal(Proposal):

    class Meta:
        verbose_name = "FPGA Miniconf Proposal"


class DevDevProposal(Proposal):

    class Meta:
        verbose_name = "Developers Developers Miniconf Proposal"


class ArtTechProposal(Proposal):

    TYPE_TECH = 1
    TYPE_DEMO = 2
    TYPE_LIGHTNING = 3

    TALK_FORMATS = [
        (TYPE_TECH, "Tech talk (45 min)"),
        (TYPE_DEMO, "Demonstration (20min)"),
        (TYPE_LIGHTNING, "Lightning Talk (10min)"),
    ]

    talk_format = models.IntegerField(
        choices=TALK_FORMATS,
        default=TYPE_TECH,
    )

    EXHIBIT_YES = 1
    EXHIBIT_NO = 2

    EXHIBIT_STATUS = [
        (EXHIBIT_YES, "I am willing and able to exhibit my project on Monday, January 22nd"),
        (EXHIBIT_NO, "I'm unable to exhibit my project")
    ]

    can_exhibit = models.IntegerField(
        choices=EXHIBIT_STATUS,
        default=EXHIBIT_YES,
    )

    exhibition_requirements = models.TextField(
        blank=True,
        default="",
    )

    TARGET_NA = 1

    TARGET_AUDIENCES = [
        (TARGET_NA, "N/A"),
    ]

    target_audience = models.IntegerField(choices=TARGET_AUDIENCES, default=TARGET_NA)

    # def __init__(self, *args, **kwargs):
    #     super(ArtTechProposal, self).__init__(*args, **kwargs)
    #     self.target_audience = 3

    class Meta:
        verbose_name = "Art+Tech Miniconf Proposal"


class BioInformaticsProposal(Proposal):

    class Meta:
        verbose_name = "Open Source and BioInformatics Miniconf"

pinaxcon/proposals/forms.py
import copy

from django import forms

from pinaxcon.proposals.models import TalkProposal, TutorialProposal, MiniconfProposal
from pinaxcon.proposals.models import SysAdminProposal, KernelProposal, OpenHardwareProposal
from pinaxcon.proposals.models import GamesProposal, ClsXLCAProposal, FuncProgProposal
from pinaxcon.proposals.models import OpenEdProposal, OpenGLAMProposal, FPGAProposal, DevDevProposal
from pinaxcon.proposals.models import ArtTechProposal, BioInformaticsProposal

DEFAULT_FIELDS =  [
    "title",
    "target_audience",
    "abstract",
    "private_abstract",
    "technical_requirements",
    "project",
    "project_url",
    "recording_release",
    "materials_release",
]

TALK_FORMAT_FIELDS = copy.copy(DEFAULT_FIELDS)
TALK_FORMAT_FIELDS.append("talk_format")

class ProposalForm(forms.ModelForm):

    required_css_class = 'label-required'

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class MiniconfProposalForm(ProposalForm):

    class Meta:
        model = MiniconfProposal
        fields = [
            "title",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "recording_release",
            "materials_release",
        ]

class SysadminProposalForm(ProposalForm):

    class Meta:
        model = SysAdminProposal
        fields = TALK_FORMAT_FIELDS

class KernelProposalForm(ProposalForm):

    class Meta:
        model = KernelProposal
        fields = DEFAULT_FIELDS

class GamesProposalForm(ProposalForm):

    class Meta:
        model = GamesProposal
        fields = TALK_FORMAT_FIELDS

class OpenHardwareProposalForm(ProposalForm):

    class Meta:
        model = OpenHardwareProposal
        fields = TALK_FORMAT_FIELDS

class ClsXLCAProposalForm(ProposalForm):

    class Meta:
        model = ClsXLCAProposal
        fields = DEFAULT_FIELDS

class FuncProgProposalForm(ProposalForm):

    class Meta:
        model = FuncProgProposal
        fields = DEFAULT_FIELDS

class OpenEdProposalForm(ProposalForm):

    class Meta:
        model = OpenEdProposal 
        fields = DEFAULT_FIELDS

class OpenGLAMProposalForm(ProposalForm):

    class Meta:
        model = OpenGLAMProposal
        fields = DEFAULT_FIELDS

class FPGAProposalForm(ProposalForm):

    class Meta:
        model = FPGAProposal
        fields = DEFAULT_FIELDS

class DevDevProposalForm(ProposalForm):

    class Meta:
        model = DevDevProposal
        fields = DEFAULT_FIELDS

class ArtTechProposalForm(ProposalForm):

    class Meta:
        ARTTECH_FIELDS = copy.copy(DEFAULT_FIELDS)
        ARTTECH_FIELDS.remove("target_audience")
        ARTTECH_FIELDS.append("talk_format")
        ARTTECH_FIELDS.append("can_exhibit")
        ARTTECH_FIELDS.append("exhibition_requirements")

        model = ArtTechProposal
        fields = ARTTECH_FIELDS

class BioInformaticsProposalForm(ProposalForm):

    class Meta:
        model = BioInformaticsProposal
        fields = DEFAULT_FIELDS

pinaxcon/registrasion/forms.py
from pinaxcon.registrasion import models

from django import forms


class YesNoField(forms.TypedChoiceField):

    def __init__(self, *args, **kwargs):
        kwargs['required'] = True
        super(YesNoField, self).__init__(
            *args,
            coerce=lambda x: x in ['True', 'Yes', True],
            choices=((None, '--------'), (False, 'No'), (True, 'Yes')),
            **kwargs
        )


class ProfileForm(forms.ModelForm):
    ''' A form for requesting badge and profile information. '''

    required_css_class = 'label-required'

    class Meta:
        model = models.AttendeeProfile
        exclude = ['attendee']
        widgets = {
            'past_lca': forms.widgets.CheckboxSelectMultiple
        }
        field_classes = {
            "of_legal_age": YesNoField,
        }

pinaxcon/registrasion/views.py
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from registrasion import models as rego
from registrasion.controllers.invoice import InvoiceController

from pinaxcon.registrasion import models


def demopay(request, invoice_id, access_code):
    ''' Marks the invoice with the given invoice id as paid.
    '''
    invoice_id = int(invoice_id)
    inv = get_object_or_404(rego.Invoice.objects, pk=invoice_id)

    invoice = InvoiceController(inv)

    if not invoice.can_view(user=request.user, access_code=access_code):
        raise Http404()

    to_invoice = redirect("invoice", invoice.invoice.id, access_code)

    try:
        invoice.validate_allowed_to_pay()  # Verify that we're allowed to do this.
    except ValidationError as ve:
        messages.error(request, ve.message)
        return to_invoice

    # Create the payment object
    models.DemoPayment.objects.create(
        invoice=invoice.invoice,
        reference="Demo payment by user: " + request.user.username,
        amount=invoice.invoice.value,
    )

    invoice.update_status()

    messages.success(request, "This invoice was successfully paid.")

    return to_invoice

pinaxcon/templates/symposion/proposals/_pending_proposal_row.html
{% load i18n %}

<div class="col-xs-12 col-sm-6 col-lg-6">
  <div class="panel panel-warning"> <!-- Todo Make the colour relate to status of acceptance -->
    <div class="panel-heading">
      <h5>{{ proposal.title }}</h5>
    </div>
    <div class="panel-body">
      <ul>
        <li><strong>Type:</strong> {{ proposal.kind.name }}</li>
        <li>
          <strong>Status:</strong>
          {% if proposal.cancelled %}
            <span class="label label-danger">Cancelled</span>
          {% else %}
            {% if request.user == proposal.speaker.user %}
              {% if proposal.result.status == "accepted" %}
                <span class="label label-success">Accepted</span>
              {% else %}
                <span class="label label-default">Submitted</span>
              {% endif %}
            {% else %}
              <span class="label label-default">Invited</span>
            {% endif %}
          {% endif %}
        </li>
      </ul>
      <div>
        <a class="btn btn-lg btn-primary" role="button" href="{% url "proposal_detail" proposal.pk %}">View Details</a>
        {% if not proposal.cancelled %}
          <a class="btn btn-lg btn-success" role="button" href="{% url "proposal_pending_join" proposal.id %}">Accept Copresenter Invitation</a>
          <a class="btn btn-lg btn-danger" role="button" href="{% url "proposal_pending_decline" proposal.id %}">Decline Copresenter Invitation</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>

pinaxcon/templates/symposion/proposals/_proposal_fields.html
{% load i18n %}
{% load lca2018_tags %}

    <div>
      <label class="col-sm-2 col-lg-2">Withdrawn</label>
      <div class="col-sm-10 col-lg-10">
          {% if proposal.cancelled %}
            <p class="label-danger">WITHDRAWN</p>
          {% else %}
            <p class="label-success">Not withdrawn</p>
          {% endif %}
      </div>
    </div>

    <div>
      <label class="col-sm-2 col-lg-2">Submitted by</label>
      <div class="col-sm-10 col-lg-10">
        <p>{{ proposal.speaker }} &lt;{{ proposal.speaker.email }}&gt;</p>
      </div>
    </div>

    <div>
      <label class="col-sm-2 col-lg-2">Proposal Type</label>
      <div class="col-sm-10 col-lg-10">
        <p>{{ proposal.kind.name|capfirst }}</p>
      </div>
    </div>

    <div>
      <label class="col-sm-2 col-lg-2">Target Audience</label>
      <div class="col-sm-10 col-lg-10">
        <p>{{ proposal.get_target_audience_display }}&nbsp;</p>
      </div>
    </div>

    {% if proposal.talk_format %}
    <div>
      <label class="col-sm-2 col-lg-2">Talk Format</label>
      <div class="col-sm-10 col-lg-10">
          <p>{{ proposal.get_talk_format_display }}</p>
      </div>
    </div>
    {% endif %}

    {% if proposal.can_exhibit %}
    <div>
      <label class="col-sm-2 col-lg-2">Can exhibit?</label>
      <div class="col-sm-10 col-lg-10">
          <p>{{ proposal.get_can_exhibit_display }}</p>
      </div>
      <div>
      <label class="col-sm-2 col-lg-2">Exhibition Requirements</label>
      <div class="col-sm-10 col-lg-10">
          {% if proposal.exhibition_requirements %}
            <div class="special_requirements monospace-text">{{ proposal.exhibition_requirements|safe }}</div>
          {% else %}
            <div class="special_requirements monospace-text"><b>No Special Talk Requirements Requested</b></div>
          {% endif %}
      
      </div>
      &nbsp;
    </div>

    </div>
    {% endif %}

    {% if proposal.additional_speakers.all %}
      <div>
        <label class="col-sm-2 col-lg-2">Additional Speakers</label>
        <div class="col-sm-10 col-lg-10">
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {% for speaker in proposal.additional_speakers.all %}
                <tr>
                  {% if speaker.user %}
                    <td>{{ speaker.name }}</td>
                    <td>{{ speaker.email }}</td>
                    <td>Joined</td>
                  {% else %}
                    <td>Unknown</td>
                    <td>{{ speaker.email }}</td>
                    <td>Invitation Sent</td>
                  {% endif %}
               </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <p></p>
    {% endif %}

    <div>
      <label class="col-sm-2 col-lg-2">Abstract</label>
      <div class="col-sm-10 col-lg-10">
        <div class="abstract monospace-text well">{{ proposal.abstract_html|safe }}&nbsp;</div>
        <p></p>
      </div>
    </div>

    <div>
      <label class="col-sm-2 col-lg-2">Private Abstract</label>
      <div class="col-sm-10 col-lg-10">
        <div class="private_abstract monospace-text well">{{ proposal.private_abstract_html|safe }}&nbsp;</div>
        <p></p>
      </div>
    </div>

    <div>
      <label class="col-sm-2 col-lg-2">Project</label>
      <div class="col-sm-10 col-lg-10">
        {% if proposal.project %}
          <p>{{ proposal.project|safe }}&nbsp;</p>
        {% else %}
          <p><b>None Provided</b></p>
        {% endif %}
      </div>
    </div>

    <div>
      <label class="col-sm-2 col-lg-2">Project URL</label>
      <div class="col-sm-10 col-lg-10">
        {% if proposal.project_url %}
          <p><a href="{{ proposal.project_url|safe }}">{{ proposal.project_url|safe }}</a>&nbsp;</p>
        {% else %}
          <p><b>None Provided</b></p>
        {% endif %}
      </div>
    </div>

    <div>
      <label class="col-sm-2 col-lg-2">Video URL</label>
      <div class="col-sm-10 col-lg-10">
        {% if proposal.video_url %}
          <p><a href="{{ proposal.video_url|safe }}">{{ proposal.video_url|safe }}</a>&nbsp;</p>
        {% else %}
          <p><b>None Provided</b></p>
        {% endif %}
      </div>
    </div>

    <div>
      <label class="col-sm-2 col-lg-2">Special Requirements</label>
      <div class="col-sm-10 col-lg-10">
        {% if proposal.technical_requirements_html %}
          <div class="special_requirements monospace-text">{{ proposal.technical_requirements_html|safe }}</div>
        {% else %}
          <div class="special_requirements monospace-text"><b>No Special Talk Requirements Requested</b></div>
        {% endif %}
      </div>
      &nbsp;
    </div>
    <br/>

    {% for speaker in proposal.speakers %}
      {% if speaker.name %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Speaker: {{ speaker.name }}</h3>
          </div>
          <div class="panel-body">
            <div>
              <label class="col-sm-2 col-lg-2">Biography</label>
              <div class="col-sm-10 col-lg-10 well monospace-text">{{ speaker.biography_html|safe }}&nbsp;</div>
            </div>
            <div>
              <label class="col-sm-2 col-lg-2">Experience</label>
              <div class="col-sm-10 col-lg-10 well monospace-text">{{ speaker.experience_html|safe }}&nbsp;</div>
            </div>
            {% if speaker.accessibility_html %}
              <div>
                <label class="col-sm-2 col-lg-2">Accessibility Requirements</label>
                <div class="col-sm-10 col-lg-10 well monospace-text">{{ speaker.accessibility_html|safe }}&nbsp;</div>
              </div>
            {% endif %}
          </div>
        </div>
      {% endif %}
    {% endfor %}

    {% can_manage proposal as can_manage_proposal %}
    {% if can_manage_proposal or request.user.speaker_profile in proposal.speakers %}
      <div>
        <label class="col-sm-2 col-lg-2">Travel Assistance Required</label>
        <div class="col-sm-10 col-lg-10">
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Travel</th>
                <th>Accomodation</th>
              </tr>
            </thead>
            <tbody>
              {% for speaker in proposal.speakers %}
                <tr>
                  {% if speaker.user %}
                    <td>{{ speaker.name }}</td>
                    <td>{{ speaker.travel_assistance }}</td>
                    <td>{{ speaker.accommodation_assistance }}</td>
                  {% else %}
                    <td><b>Unconfirmed co-presenter</b></td>
                    <td><b>Unknown</b></td>
                    <td><b>Unknown</b></td>
                  {% endif %}
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <br />
    {% endif %}

    <div>
      <label class="col-sm-2 col-lg-2">Recording Release</label>
      <div class="col-sm-10 col-lg-10">
        <p>{{ proposal.recording_release }}&nbsp;</p>
      </div>
      &nbsp;
    </div>

    <div>
      <label class="col-sm-2 col-lg-2">Materials Release</label>
      <div class="col-sm-10 col-lg-10">
        <p>{{ proposal.materials_release }}&nbsp;</p>
      </div>
      &nbsp;
    </div>

pinaxcon/templates/symposion/proposals/_proposal_row.html
<div class="col-xs-12 col-sm-6 col-lg-6">
  {% if proposal.result.status == "accepted" %}
    <div class="panel panel-success">
  {% elif proposal.result.status == "rejected" %}
    <div class="panel panel-danger">
  {% elif proposal.result.status == "standby" %}
    <div class="panel panel-warning">
  {% else %}
    <div class="panel panel-primary">
  {% endif %}
    <div class="panel-heading">
      <h5>{{ proposal.title }}</h5>
    </div>
    <div class="panel-body">
      <ul>
        <li><strong>Type:</strong> {{ proposal.kind.name }}</li>
        <li>
          <strong>Status:</strong>
          {% if proposal.cancelled %}
            <span class="label label-danger">Cancelled</span>
          {% else %}
            {% if request.user == proposal.speaker.user %}
              {% if proposal.result.status == "accepted" %}
                <span class="label label-success">Accepted</span>
              {% elif proposal.result.status == "rejected" %}
                <span class="label label-danger">Rejected</span>
              {% elif proposal.result.status == "standby" %}
                <span class="label label-warning">Standby</span>
              {% else %}
                <span class="label label-default">Submitted</span>
              {% endif %}
            {% else %}
              <span class="label label-default">Associated</span>
            {% endif %}
          {% endif %}
        </li>
      </ul>
      <div>
        <a class="btn btn-lg btn-success" role="button" href="{% url "proposal_detail" proposal.pk %}">View Details</a>
        {% if not proposal.cancelled %}
          {% if request.user == proposal.speaker.user and proposal.can_edit %}
            <a class="btn btn-lg btn-success" role="button" href="{% url "proposal_edit" proposal.pk %}">Edit</a>
            <a class="btn btn-lg btn-success" role="button" href="{% url "proposal_speaker_manage" proposal.id %}">Manage Additional Speakers</a>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
</div>

pinaxcon/templates/symposion/proposals/base.html
{% extends "utility_page.html" %}
{% load staticfiles %}


{% block utility_body_outer %}
{% block proposals_body_outer %}
  <div class="l-content-page">
    <div class="l-content-page--richtext">
      {% block utility_body %}
        {% block proposals_body %}
        {% endblock %}
      {% endblock %}
    </div>
  </div>
{% endblock %}
{% endblock %}

pinaxcon/templates/symposion/proposals/document_create.html
{% extends "symposion/proposals/base.html" %}

{% block page_title %}Upload Document to '{{ proposal.title }}'{% endblock %}

{% block proposals_body %}
    <form class="form-horizontal" method="POST" action="" enctype="multipart/form-data" class="form form-horizontal">
        {% csrf_token %}
        <fieldset>
          {% include "_form_snippet.html" with form=form %}
          <div class="btn-group">
              <input class="btn btn-primary" type="submit" value="Upload" />
          </div>
        </fieldset>
    </form>
{% endblock %}

pinaxcon/templates/symposion/proposals/proposal_cancel.html
{% extends "symposion/proposals/base.html" %}

{% load i18n %}

{% block head_title %}{% trans 'Cancel Proposal' %}{% endblock %}
{% block page_title %}Cancel: {{ proposal.title }}{% endblock %}

{% block proposals_body %}
    <form class="form-horizontal" method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you want to cancel <b>{{ proposal.title }}</b>?</p>
        <input class="btn btn-danger" type="submit" value="I am sure" />
        <a class="btn btn-default" href="{% url "proposal_detail" proposal.pk %}">{% trans 'No, keep it for now' %}</a>
    </form>
{% endblock %}

pinaxcon/templates/symposion/proposals/proposal_edit.html
{% extends "symposion/proposals/base.html" %}

{% block head_title %}Editing {{ proposal.title }}{% endblock %}
{% block page_title %}Editing: {{ proposal.title }}{% endblock %}

{% block proposals_body %}
  <p><a href="{% url "proposal_speaker_manage" proposal.pk %}">Manage speakers</a></p>

  <form class="form-horizontal" method="POST" action="" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset>
        {% include "_form_snippet.html" with form=form %}
        <div class="btn-group">
            <input class="btn btn-primary" type="submit" value="Save" />
            <a class="btn btn-default" href="{% url "proposal_detail" proposal.pk %}">Cancel</a>
        </div>
      </fieldset>

  </form>
{% endblock %}

pinaxcon/templates/symposion/proposals/proposal_leave.html
{% extends "symposion/proposals/base.html" %}

{% block page_title %}Leaving {{ proposal.title }}{% endblock %}
{% block head_title %}Leaving {{ proposal.title }}{% endblock %}

{% block body %}
    <form class="form-horizontal" method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you wish to leave as a speaker on <b>{{ proposal.title }}</b>?</p>
        <input type="submit" class="btn btn-primary" value="I am sure" />
    </form>
{% endblock %}

pinaxcon/templates/symposion/proposals/proposal_submit.html
{% extends "symposion/proposals/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Submit A Proposal" %}{% endblock %}
{% block header_title %}Submit A Proposal{% endblock %}

{% block proposals_body %}

    {% if kinds %}
        <h1>Select what kind of proposal you'd like to submit:</h1>
        {% for kind in kinds %}
            <a class="btn btn-lg btn-primary" role="button" href="{% url "proposal_submit_kind" kind.slug %}">{{ kind }}</a>
        {% endfor %}
    {% else %}
        <h1>Proposals are not currently open for submission.</h1>
    {% endif %}
{% endblock %}