pinaxcon/registrasion/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    "pinaxcon.registrasion.views",
    url(r"^demopay/([0-9]+)/([A-Z0-9]+)$", views.demopay, name="demopay"),
)

pinaxcon/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.contrib.flatpages.views import flatpage

from django.contrib import admin

import symposion.views


urlpatterns = [
    url(r'^saml2/', include('djangosaml2.urls')),
    url(r"^admin/", include(admin.site.urls)),

    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^conference/", include("symposion.conference.urls")),

    url(r"^teams/", include("symposion.teams.urls")),

    # Required by registrasion
    url(r'^tickets/payments/', include('registripe.urls')),
    url(r'^tickets/', include('registrasion.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^checkin/', include('regidesk.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    url(r'^dashboard/', symposion.views.dashboard, name="dashboard"),
    url(r'^boardingpass', RedirectView.as_view(pattern_name="regidesk:boardingpass")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, url(r'^__debug__/', include(debug_toolbar.urls)))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinaxcon/registrasion/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django_countries.fields import CountryField
from registrasion import models as rego


@python_2_unicode_compatible
class PastEvent(models.Model):
    ''' This is populated in 0001_initial.py '''

    def __str__(self):
        return self.name

    year = models.IntegerField(unique=True,)
    name = models.CharField(max_length=255, unique=True,)


class AttendeeProfile(rego.AttendeeProfileBase):

    @classmethod
    def name_field(cls):
        ''' This is used to pre-fill the attendee's name from the
        speaker profile. If it's None, that functionality is disabled. '''
        return "name"

    def invoice_recipient(self):

        lines = [
            self.name_per_invoice,
        ]

        if self.company:
            lines.append("C/- " + self.company)

        if self.address_line_1:
            lines.append(self.address_line_1)

        if self.address_line_2:
            lines.append(self.address_line_2)

        if self.address_suburb or self.address_postcode:
            lines.append("%s %s" % (
                self.address_suburb or "",
                self.address_postcode or "",
            ))

        if self.state:
            lines.append(self.state)

        if self.country:
            lines.append(self.country.name)

        return "\n".join(lines)

    def clean(self):
        errors = []
        if self.country == "AU" and not self.state:
            errors.append(
                ("state", "Australians must list their state"),
            )

        if self.address_line_2 and not self.address_line_1:
            errors.append((
                "address_line_1",
                "Please fill in line 1 before filling line 2",
            ))

        if errors:
            raise ValidationError(dict(errors))

    def save(self):
        if not self.name_per_invoice:
            self.name_per_invoice = self.name
        super(AttendeeProfile, self).save()

    # Things that appear on badge
    name = models.CharField(
        verbose_name="Your name (for your conference nametag)",
        max_length=64,
        help_text="Your name, as you'd like it to appear on your badge. ",
    )
    company = models.CharField(
        max_length=64,
        help_text="The name of your company, as you'd like it on your badge",
        blank=True,
    )

    free_text_1 = models.CharField(
        max_length=64,
        verbose_name="Free text line 1",
        help_text="A line of free text that will appear on your badge. Use "
                  "this for your Twitter handle, IRC nick, your preferred "
                  "pronouns or anything else you'd like people to see on "
                  "your badge.",
        blank=True,
    )
    free_text_2 = models.CharField(
        max_length=64,
        verbose_name="Free text line 2",
        blank=True,
    )

    # Other important Information
    name_per_invoice = models.CharField(
        verbose_name="Your legal name (for invoicing purposes)",
        max_length=256,
        help_text="If your legal name is different to the name on your badge, "
                  "fill this in, and we'll put it on your invoice. Otherwise, "
                  "leave it blank.",
        blank=True,
        )

    address_line_1 = models.CharField(
        verbose_name="Address line 1",
        help_text="This address, if provided, will appear on your invoices.",
        max_length=1024,
        blank=True,
    )
    address_line_2 = models.CharField(
        verbose_name="Address line 2",
        max_length=1024,
        blank=True,
    )
    address_suburb = models.CharField(
        verbose_name="City/Town/Suburb",
        max_length=1024,
        blank=True,
    )
    address_postcode = models.CharField(
        verbose_name="Postal/Zip code",
        max_length=1024,
        blank=True,
    )
    country = CountryField(
        default="AU",
    )
    state = models.CharField(
        max_length=256,
        verbose_name="State/Territory/Province",
        help_text="If your Country is Australia, you must list a state.",
        blank=True,
    )

    of_legal_age = models.BooleanField(
        verbose_name="Are you over 18?",
        help_text="Being under 18 will not stop you from attending the "
                  "conference. We need to know whether you are over 18 to "
                  "allow us to cater for you at venues that serve alcohol.",
    )
    dietary_restrictions = models.CharField(
        verbose_name="Food allergies, intolerances, or dietary restrictions",
        max_length=256,
        blank=True,
    )
    accessibility_requirements = models.CharField(
        verbose_name="Accessibility-related requirements",
        max_length=256,
        blank=True,
    )
    gender = models.CharField(
        help_text="Gender data will only be used for demographic purposes.",
        max_length=64,
        blank=True,
    )

    linux_australia = models.BooleanField(
        verbose_name="Linux Australia membership",
        help_text="Select this field to register for free "
                  "<a href='http://www.linux.org.au/'>Linux Australia</a> "
                  "membership.",
        blank=True,
    )

    lca_announce = models.BooleanField(
        verbose_name="Subscribe to lca-announce list",
        help_text="Select to be subscribed to the low-traffic lca-announce "
                  "mailing list",
        blank=True,
    )

    lca_chat = models.BooleanField(
        verbose_name="Subscribe to the lca2018-chat list",
        help_text="lca2018-chat is a high-traffic mailing list used by "
                  "attendees during the week of the conference for general "
                  "discussion.",
        blank=True,
    )

    future_conference = models.BooleanField(
        verbose_name = "Reuse my login for future Linux Australia conferences?",
        help_text="Select to have your login details made available to future "
                  "Linux Australia conferences who share the same Single Sign "
                  "On system.",
        blank=True,
    )

    past_lca = models.ManyToManyField(
        PastEvent,
        verbose_name="Which past linux.conf.au events have you attended?",
        blank=True,
    )

pinaxcon/proposals/forms.py
import copy

from django import forms

from pinaxcon.proposals.models import TalkProposal, TutorialProposal, MiniconfProposal
from pinaxcon.proposals.models import SysAdminProposal, KernelProposal, OpenHardwareProposal
from pinaxcon.proposals.models import GamesProposal, ClsXLCAProposal, FuncProgProposal
from pinaxcon.proposals.models import OpenEdProposal, OpenGLAMProposal, FPGAProposal, DevDevProposal
from pinaxcon.proposals.models import ArtTechProposal, BioInformaticsProposal

DEFAULT_FIELDS =  [
    "title",
    "target_audience",
    "abstract",
    "private_abstract",
    "technical_requirements",
    "project",
    "project_url",
    "recording_release",
    "materials_release",
]

TALK_FORMAT_FIELDS = copy.copy(DEFAULT_FIELDS)
TALK_FORMAT_FIELDS.append("talk_format")

class ProposalForm(forms.ModelForm):

    required_css_class = 'label-required'

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class MiniconfProposalForm(ProposalForm):

    class Meta:
        model = MiniconfProposal
        fields = [
            "title",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "recording_release",
            "materials_release",
        ]

class SysadminProposalForm(ProposalForm):

    class Meta:
        model = SysAdminProposal
        fields = TALK_FORMAT_FIELDS

class KernelProposalForm(ProposalForm):

    class Meta:
        model = KernelProposal
        fields = DEFAULT_FIELDS

class GamesProposalForm(ProposalForm):

    class Meta:
        model = GamesProposal
        fields = TALK_FORMAT_FIELDS

class OpenHardwareProposalForm(ProposalForm):

    class Meta:
        model = OpenHardwareProposal
        fields = TALK_FORMAT_FIELDS

class ClsXLCAProposalForm(ProposalForm):

    class Meta:
        model = ClsXLCAProposal
        fields = DEFAULT_FIELDS

class FuncProgProposalForm(ProposalForm):

    class Meta:
        model = FuncProgProposal
        fields = DEFAULT_FIELDS

class OpenEdProposalForm(ProposalForm):

    class Meta:
        model = OpenEdProposal 
        fields = DEFAULT_FIELDS

class OpenGLAMProposalForm(ProposalForm):

    class Meta:
        model = OpenGLAMProposal
        fields = DEFAULT_FIELDS

class FPGAProposalForm(ProposalForm):

    class Meta:
        model = FPGAProposal
        fields = DEFAULT_FIELDS

class DevDevProposalForm(ProposalForm):

    class Meta:
        model = DevDevProposal
        fields = DEFAULT_FIELDS

class ArtTechProposalForm(ProposalForm):

    class Meta:
        ARTTECH_FIELDS = copy.copy(DEFAULT_FIELDS)
        ARTTECH_FIELDS.remove("target_audience")
        ARTTECH_FIELDS.append("talk_format")
        ARTTECH_FIELDS.append("can_exhibit")
        ARTTECH_FIELDS.append("exhibition_requirements")

        model = ArtTechProposal
        fields = ARTTECH_FIELDS

class BioInformaticsProposalForm(ProposalForm):

    class Meta:
        model = BioInformaticsProposal
        fields = DEFAULT_FIELDS

pinaxcon/registrasion/forms.py
from pinaxcon.registrasion import models

from django import forms


class YesNoField(forms.TypedChoiceField):

    def __init__(self, *args, **kwargs):
        kwargs['required'] = True
        super(YesNoField, self).__init__(
            *args,
            coerce=lambda x: x in ['True', 'Yes', True],
            choices=((None, '--------'), (False, 'No'), (True, 'Yes')),
            **kwargs
        )


class ProfileForm(forms.ModelForm):
    ''' A form for requesting badge and profile information. '''

    required_css_class = 'label-required'

    class Meta:
        model = models.AttendeeProfile
        exclude = ['attendee']
        widgets = {
            'past_lca': forms.widgets.CheckboxSelectMultiple
        }
        field_classes = {
            "of_legal_age": YesNoField,
        }

pinaxcon/registrasion/views.py
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from registrasion import models as rego
from registrasion.controllers.invoice import InvoiceController

from pinaxcon.registrasion import models


def demopay(request, invoice_id, access_code):
    ''' Marks the invoice with the given invoice id as paid.
    '''
    invoice_id = int(invoice_id)
    inv = get_object_or_404(rego.Invoice.objects, pk=invoice_id)

    invoice = InvoiceController(inv)

    if not invoice.can_view(user=request.user, access_code=access_code):
        raise Http404()

    to_invoice = redirect("invoice", invoice.invoice.id, access_code)

    try:
        invoice.validate_allowed_to_pay()  # Verify that we're allowed to do this.
    except ValidationError as ve:
        messages.error(request, ve.message)
        return to_invoice

    # Create the payment object
    models.DemoPayment.objects.create(
        invoice=invoice.invoice,
        reference="Demo payment by user: " + request.user.username,
        amount=invoice.invoice.value,
    )

    invoice.update_status()

    messages.success(request, "This invoice was successfully paid.")

    return to_invoice

pinaxcon/templates/403_csrf.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% load i18n %}

{% block body_class %}template-blogpage{% endblock %}

{% block head_title %}{{ page.title }}{% endblock %}

{% block body %}
  {% block content %}
    <div class="l-content-page">
      <div class="l-content-page--richtext">
        <h2>{{ title }} <span>(403)</span></h2>

        <p>{{ main }}</p>

        {% if bad_token and request.user.is_authenticated %}
          <p>You are already logged in. If you saw this issue whilst attempting
            to log in, you can to go to the
            <a href='{% url "dashboard" %}'>Dashboard</a> and continue using
            the site.</p>
        {% endif %}

        {% if no_referer %}
          <p>{{ no_referer1 }}</p>
          <p>{{ no_referer2 }}</p>
        {% endif %}
        {% if no_cookie %}
          <p>{{ no_cookie1 }}</p>
          <p>{{ no_cookie2 }}</p>
        {% endif %}

        {% if DEBUG %}
          <h2>Help</h2>
            {% if reason %}
            <p>Reason given for failure:</p>
            <pre>
            {{ reason }}
            </pre>
            {% endif %}
          <p>In general, this can occur when there is a genuine Cross Site Request Forgery, or when
          <a
          href="https://docs.djangoproject.com/en/{{ docs_version }}/ref/csrf/">Django's
          CSRF mechanism</a> has not been used correctly.  For POST forms, you need to
          ensure:</p>
          <ul>
            <li>Your browser is accepting cookies.</li>
            <li>The view function passes a <code>request</code> to the template's <a
            href="https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render"><code>render</code></a>
            method.</li>
            <li>In the template, there is a <code>{% templatetag openblock %} csrf_token
            {% templatetag closeblock %}</code> template tag inside each POST form that
            targets an internal URL.</li>
            <li>If you are not using <code>CsrfViewMiddleware</code>, then you must use
            <code>csrf_protect</code> on any views that use the <code>csrf_token</code>
            template tag, as well as those that accept the POST data.</li>
          </ul>
          <p>You're seeing the help section of this page because you have <code>DEBUG =
          True</code> in your Django settings file. Change that to <code>False</code>,
          and only the initial error message will be displayed.  </p>
          <p>You can customize this page using the CSRF_FAILURE_VIEW setting.</p>
        {% else %}
          <p><small>{{ more }}</small></p>
        {% endif %}
      </div>
    </div>
  {% endblock %}
{% endblock %}

pinaxcon/templates/_form_btns.html
<input class="btn btn-primary" type="submit" value="Save" />
          <a class="btn btn-default" href="{% url "dashboard" %}">Cancel</a>

pinaxcon/templates/_form_snippet.html
{% load lca2018_tags %}
{% load bootstrap %}
{% load crispy_forms_tags %}

{% if form.non_field_errors %}
  <div class="has-errors">
    {{ form.non_field_errors }}
  </div>
  <br/>
{% endif %}

<blockquote>
  Fields marked with a<br/>* are required
</blockquote>

{% crispy form %}

pinaxcon/templates/dashboard.html
{% extends "utility_page.html" %}
{% load staticfiles %}
{% load i18n %}
{% load proposal_tags %}
{% load review_tags %}
{% load teams_tags %}
{% load registrasion_tags %}
{% load lca2018_tags %}
{% load staticfiles %}


{% block header_title %}linux.conf.au 2019{% endblock %}
{% block header_lead %}User Dashboard{% endblock %}
{% block main_class %}{% endblock %}

{% block content %}

{% available_categories as categories %}
<div class="container">
<h1 class="text-primary mb-5">Dashboard</h1>
</div>
{% if categories %} 

{% if user.is_staff %}
<div class="container">
  <h2>Administration</h2>
  <div class="page-row">
    <div class="col-xs-12">
      <a class="btn btn-lg btn-info" role="button" href="{% url "reports_list" %}">Reports</a>
    </div>
  </div>
</div>
{% endif %}

<div class="container">
  <div class="col-12">
    <h2>{% trans "Attend" %} {% conference_name %}</h2>
  </div>
  <div class="page-row">
    {% if not user.attendee.completed_registration %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Register</h4>
      </div>
      <div class="panel-body">
        <p>To attend the conference, you must create an attendee profile and purchase your ticket</p>
        <a class="btn btn-lg btn-success" role="button" href="{% url "guided_registration" %}">Get your ticket</a>
      </div>
    </div>
    {% else %}
    <div class="col-xs-12 col-sm-6 col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Attendee Profile</h4>
        </div>
        <div class="panel-body">
          <p>If you would like to change the details on your badge or your attendee statistics, you may edit your attendee profile up until the 15th January 2018</p>
          <a class="btn btn-lg btn-primary pull-left" role="button" href="{% url "user_badge" %}">Preview my badge</a>
          <a class="btn btn-lg btn-primary pull-right" role="button" href="{% url "attendee_edit" %}">Edit attendee profile</a>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Account Management</h4>
        </div>
        <div class="panel-body">
          <p>If you would like to change your registered email address or password, you can use our self-service account management portal</p>
          <a class="btn btn-lg btn-primary pull-right" role="button" href="https://login.linux.conf.au/manage/">Account Management</a>
        </div>
      </div>
    </div>
    
    {% items_pending as pending %}
    
    <div class="col-xs-12 col-sm-12 col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Account</h4>
        </div>
        <div class="panel-body">
          
          {% if pending %}
          <div class="col-xs-12 col-sm-6 col-lg-6">
            <div class="panel panel-warning">
              <div class="panel-heading">
                <h5>Items pending payment</h5>
              </div>
              <div class="panel-body">
                {% include "registrasion/_items_list.html" with items=pending %}
                <div class="right">
                  <a class="btn btn-lg btn-success pull-right" role="button" href="{% url "checkout" %}">Check out and pay</a>
                </div>
              </div>
            </div>
          </div>
          {% endif %}
          
          {% items_purchased as purchased %}
          {% if purchased %}
          <div class="col-xs-12 col-sm-6 col-lg-6">
            <div class="panel panel-success">
              <div class="panel-heading">
                <h5>Paid Items</h5>
              </div>
              <div class="panel-body">
                {% include "registrasion/_items_list.html" with items=purchased %}
              </div>
            </div>
          </div>
          {% endif %}
          <div class="col-xs-12 col-sm-6 col-lg-6">
            <div class="panel panel-success">
              <div class="panel-heading">
                <h5>Add/Update Items</h5>
              </div>
              <div class="panel-body">
                {% include "registrasion/_category_list.html" with categories=categories %}
              </div>
            </div>
          </div>
          
          {% invoices as invoices %}
          {% if invoices %}
          <div class="col-xs-12 col-sm-12 col-lg-12">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h5>Invoices</h5>
              </div>
              <div class="panel-body">
                <ul>
                  {% for invoice in invoices %}
                  {% if invoice.is_void %}
                  <li class="void-invoice" style="display: none;">
                    {% else %}
                    <li>
                      {% endif %}
                      <a href="{% url "invoice" invoice.id %}" >Invoice {{ invoice.id }}</a>
                      - ${{ invoice.value }} ({{ invoice.get_status_display }})
                    </li>
                    {% endfor %}
                  </ul>
                  <button id="toggle-void-invoices" onclick="toggleVoidInvoices();">Show void invoices</button>
                </div>
              </div>
            </div>
            {% endif %}
            
            {% available_credit as credit %}
            {% if credit %}
            <div class="col-xs-12 col-sm-12 col-lg-12">
              <div class="panel panel-danger">
                <div class="panel-heading">
                  <h5>Credit</h5>
                </div>
                <div class="panel-body">
                  <p>You have ${{ credit }} leftover from refunded invoices. This credit will be automatically applied to new invoices. Contact the conference organisers to for a refund to your original payment source.</p>
                </div>
              </div>
            </div>
            {% endif %}
            
          </div>
        </div>
      </div>
      
      {% endif %}
  </div>
</div>
  {% endif %}
  

<div class="container">
<div class="row">
    <div class="col-12">
      <h2 class="text-primary mb-5">{% trans "Speaking and Miniconfs" %}</h2>
    </div>
</div>
  
<div class="row">
    <div class="col-md-6 text-primary d-flex flex-column">
      <h3 class="text-upper">Speaker Profile</h3>
      {% if not user.speaker_profile %}
      <p>
        To create a speaking or miniconf proposal you must first create a speaker 
        profile.
      </p>
      {% endif %}
      <p>
        Your speaker profile is independent of your attendee profile and the 
        details you provide here will be used during selection and to populate 
        your speaker bio on the conference website.
      </p>
      <div class="mt-auto">
        {% if not user.speaker_profile %}
        <a href="{% url "speaker_create" %}" class="btn btn-primary btn-lg" role="button">Create Profile</a>
        {% else %}
        <a href="{% url "speaker_edit" %}" class="btn btn-primary btn-lg" role="button">Edit Profile</a>
        {% endif %}
      </div>
    </div>
    
    {% if user.speaker_profile %}
    <div class="col-md-6 text-primary d-flex flex-column">
      <h3 class="text-upper">New Proposal</h3>
      <p>You may use the following form to create a speaking or miniconf proposal.</p>
      <p>Once submitted you will be able to see the status of your proposals, as well manage the submission and co-speakers from this page</p>
      <div class="mt-auto">
        <a class="btn btn-lg btn-primary" role="button" href="{% url "proposal_submit" %}">New Proposal</a>
      </div>
    </div>
    {% endif %}
</div>
</div>


{% if user.speaker_profile %}
{% if user.speaker_profile.proposals.exists %}
<div class="container">
  <div class="page-header">
    <h2>Your Proposals</h2>
  </div>
  <div class="page-row">
    {% if user.speaker_profile.proposals.exists %}
    {% for proposal in user.speaker_profile.proposals.all %}
    {% include "symposion/proposals/_proposal_row.html" %}
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endif %}
{% endif %}


{% if user.speaker_profile %}
{% associated_proposals as associated_proposals %}
{% pending_proposals as pending_proposals %}
{% if associated_proposals or pending_proposals %}
<div class="container">
  <div class="page-header">
    <h2>Copresenter Proposals</h2>
  </div>
  <div class="page-row">
    {% for proposal in associated_proposals %}
    {% include "symposion/proposals/_proposal_row.html" %}
    {% endfor %}
    {% for proposal in pending_proposals %}
    {% include "symposion/proposals/_pending_proposal_row.html" %}
    {% endfor %}
  </div>
</div>
{% endif %}
{% endif %}

{% if review_sections %}
<div class="bg-primary text-secondary mt-5 pb-5">
<div class="container">
<div class="row">
  <h2 class="col-12 my-5">{% trans "Reviews" %}</h2>
  {% for section in review_sections %}
  <div class="col-md-6">
    <h3>{{ section }}</h3>
          <ul class="list-unstyled">
            <li><a href="{% url "review_section" section.section.slug %}">All</a></li>
            <li><a href="{% url "user_reviewed" section.section.slug %}">Reviewed by you</a></li>
            <li><a href="{% url "user_not_reviewed" section.section.slug %}">Not Reviewed by you</a></li>
          </ul>
          {% if section in manage_sections %}
          <ul class="list-unstyled">
            <li><a href="{% url "review_bulk_update" section.section.slug %}">Bulk Update</a></li>
            <li><a href="{% url "result_notification" section.section.slug "accepted" %}">Send notifications</a></li>
            <li><a href="{% url "review_status" section.section.slug %}">Voting Status</a></li>
            <li><a href="{% url "review_admin" section.section.slug %}">Reviewer Stats</a></li>
          </ul>
          {% endif %}
  </div>
  {% endfor %}
</div>
{% endif %}
</div>
</div>
{% available_teams as available_teams %}
{% if user.memberships.exists or available_teams %}
<div class="container">
  <div class="page-header">
    <h2>{% trans "Teams" %}</h2>
  </div>
</div>
<div class="container">
  <div class="page-row">
    {% if user.memberships.exists %}
    <div class="page-header">
      <h3>Your Teams</h3>
    </div>
    <div clas="page-row">
      {% for membership in user.memberships.all %}
      <div class="col-xs-12 col-sm-6 col-lg-6">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h5>{{ membership.team.name }}</h5>
          </div>
          <div class="panel-body">
            {% if membership.team.description %}<p>{{ membership.team.description }}</p>{% endif %}
            <a class="btn btn-lg btn-primary" role="button" href="{% url "team_detail" membership.team.slug %}">Details</a>
            <span class="{% if membership.state == 'invited' %} label-info{% endif %}">{{ membership.get_state_display }}</span>
            {% if membership.state == "manager" or user.is_staff %}
            {% if membership.team.applicants %}{{ membership.team.applicants.count }} applicant{{ membership.team.applicants.count|pluralize }}{% endif %}
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>
<div class="container">
  <div class="page-row">
    {% if available_teams %}
    <div class="page-header">
      <h3>Available Teams</h3>
    </div>
    <div class="page-row">
      {% for team in available_teams %}
      <div class="col-xs-12 col-sm-6 col-lg-6">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h5>{{ team }}</h5>
          </div>
          <div class="panel-body">
            {% if team.description %}<p>{{ team.description }}</p>{% endif %}
            <span class="label label-default">{{ team.get_access_display }}</span>
            <a class="btn btn-lg btn-primary" role="button" href="{% url "team_detail" team.slug %}">Details</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>
{% endif %}

{% endblock %} <!-- block content -->

{% block scripts_extra %}
<script type="text/javascript">
  var _toggleVoidInvoices = function() {
    var visible = false;
    function toggleVoidInvoices() {
      $btn = $("#toggle-void-invoices");
      $invoices = $(".void-invoice")
      
      if (visible) {
        $invoices.hide();
        btnText = "Show void invoices";
      } else {
        $invoices.show();
        btnText = "Hide void invoices";
      }
      $btn.text(btnText);
      visible = !visible;
      return true;
    }
    return toggleVoidInvoices;
  }
  var toggleVoidInvoices = _toggleVoidInvoices();
  _toggleVoidInvoices = undefined;
</script>
{% endblock %}